name = "roost"
version = "0.1.0"
description = "Phoenix-channel WebSocket client for Gleam, built on Gluegun"
licences = ["MIT"]
repository = { type = "github", user = "tylerbutler", repo = "roost" }
gleam = ">= 1.7.0"
target = "erlang"
internal_modules = [
  "roost/internal",
  "roost/internal/*",
]

[dependencies]
gleam_stdlib = ">= 0.48.0 and < 2.0.0"
gleam_erlang = ">= 1.0.0 and < 2.0.0"
gleam_otp = ">= 1.0.0 and < 2.0.0"
gleam_json = ">= 3.0.0 and < 4.0.0"
gluegun = { path = "../gluegun" }

[dev-dependencies]
startest = ">= 0.8.0 and < 1.0.0"
