name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [erlang, javascript]

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # ratchet:actions/checkout@v7

      - uses: tylerbutler/actions/setup-gleam@ed7d5e5f1d4370a5ccf06503916e3c301102ab1c # ratchet:tylerbutler/actions/setup-gleam@main
        with:
          erlang-version: "27"
          gleam-version: "1.9.0"
          version-file: ""
          node: ${{ matrix.target == 'javascript' }}

      - if: matrix.target == 'erlang'
        run: gleam format --check src test

      - run: gleam check --target ${{ matrix.target }}

      - run: gleam test --target ${{ matrix.target }}

      - run: gleam build --target ${{ matrix.target }} --warnings-as-errors
