name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [erlang, javascript]

    steps:
      - uses: actions/checkout@v6

      - uses: tylerbutler/actions/setup-gleam@main
        with:
          erlang-version: "27"
          gleam-version: "1.9.0"
          version-file: ""
          node: ${{ matrix.target == 'javascript' }}

      - if: matrix.target == 'erlang'
        run: gleam format --check src test

      - run: gleam check --target ${{ matrix.target }}

      - run: gleam test --target ${{ matrix.target }}

      - run: gleam build --target ${{ matrix.target }} --warnings-as-errors
